/*
**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


 void vMainPeriodicTask1Function(void *pvParam)
 {
 	portTickType xLastWakeuptime;
 	while(1)
 	{
 		xLastWakeuptime = xTaskGetTickCount();
 		// work
 		led_toggle(LED_GREEN);
 		vTaskDelayUntil(&xLastWakeuptime, 4000 / portTICK_RATE_MS);
 	}
 	 	vTaskDelete(NULL);

 }
 		void vMainPeriodicTask3Function(void *pvParam)
 		 {
 		 	portTickType xLastWakeuptime;
 		 	while(1)
 		 	{
 		 		xLastWakeuptime = xTaskGetTickCount();
 		led_toggle(LED_BLUE);
 		vTaskDelayUntil(&xLastWakeuptime, 3000 / portTICK_RATE_MS);

 	}
 	vTaskDelete(NULL);
 }


 	void vMainPeriodicTask2Function(void *pvParam)
 	 {
 	 	portTickType xLastWakeuptime;
        while(1)
        {
        	xLastWakeuptime = xTaskGetTickCount();
 		led_toggle(LED_RED);
 		vTaskDelayUntil(&xLastWakeuptime, 2000 / portTICK_RATE_MS);
        }
vTaskDelete(NULL);
 	 }

 	void vMainPeriodicTask4Function(void *pvParam)
 	 	 {
 	 	 	portTickType xLastWakeuptime;
 	        while(1)
 	{
 	        	xLastWakeuptime = xTaskGetTickCount();
 		led_toggle(LED_ORANGE);
 		vTaskDelayUntil(&xLastWakeuptime, 1000 / portTICK_RATE_MS);

}
vTaskDelete(NULL);
 	 }



int main(void)
{
	led_init(LED_RED);
	led_init(LED_GREEN);
	led_init(LED_BLUE);
    led_init(LED_ORANGE);

	xTaskCreate(vMainPeriodicTask1Function, "Periodic", configMINIMAL_STACK_SIZE, NULL, 1, NULL);
	xTaskCreate(vMainPeriodicTask2Function, "Periodic", configMINIMAL_STACK_SIZE, NULL, 2, NULL);
	xTaskCreate(vMainPeriodicTask3Function, "Periodic", configMINIMAL_STACK_SIZE, NULL, 3, NULL);
    xTaskCreate(vMainPeriodicTask4Function, "Periodic", configMINIMAL_STACK_SIZE, NULL, 4, NULL);


	vTaskStartScheduler();
	while(1);
}








