/*
**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void toggleLED(uint8_t ledNumber);

void vLedTask(void *pvParameters)
{
    uint8_t ledNumber = ((uint8_t*)pvParameters)[0];  
    uint32_t rate = ((uint32_t*)pvParameters)[1];     

    while (1)
    {
        toggleLED(ledNumber); 
        vTaskDelay(pdMS_TO_TICKS(rate));  
    }
}

int main(void)
{

    uint8_t ledTask1Params[] = {0, 500};  
    uint8_t ledTask2Params[] = {1, 1000}; 
    uint8_t ledTask3Params[] = {2, 1500}; 
    uint8_t ledTask4Params[] = {3, 2000}; 

    xTaskCreate(vLedTask, "LED Task 1", configMINIMAL_STACK_SIZE, ledTask1Params, tskIDLE_PRIORITY, NULL);
    xTaskCreate(vLedTask, "LED Task 2", configMINIMAL_STACK_SIZE, ledTask2Params, tskIDLE_PRIORITY, NULL);
    xTaskCreate(vLedTask, "LED Task 3", configMINIMAL_STACK_SIZE, ledTask3Params, tskIDLE_PRIORITY, NULL);
    xTaskCreate(vLedTask, "LED Task 4", configMINIMAL_STACK_SIZE, ledTask4Params, tskIDLE_PRIORITY, NULL);

    vTaskStartScheduler();

    for (;;);
    return 0;
}

void toggleLED(uint8_t ledNumber)
{
    printf("Toggling LED %d\n", ledNumber);
}









